language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

os:
  - linux
#  - osx

dist: xenial

git:
  submodules: false
  lfs_skip_smudge: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

#addons:
#  apt:
#    update: true
#    packages: ffmpeg
#  homebrew:
#    packages: ffmpeg

script:
  - pytest -v -m 'not integration' tests/
  - flake8 . --exit-zero
